2025-10-14_18:15:30

diff --git a/.local/script/zapas b/.local/script/zapas
--- a/.local/script/zapas
+++ b/.local/script/zapas
@@ -1,30 +1,32 @@
 #!/bin/bash
 
-err() { echo "$1"; exit 1; }
+FILTER="$HOME/.config/backup.filter"
+SOURCE="$HOME/"
 
-usage() {
-	printf "Usage: ${0##*/} [%s]\n" "$(declare -F | cut -d" " -f3 | tr "\n" "|" | sed 's/|usage|//')"
+run() {
+	local BASE_DIR && BASE_DIR=$(realpath "$1")
+	[[ -d $BASE_DIR ]] || { echo "Invalid destination: $BASE_DIR"; exit 1; }
+
+	local DEST && DEST=$BASE_DIR/$(date +%F_%H-%M-%S)
+	local LATEST_LINK=$BASE_DIR/latest
+
+	mkdir "$DEST" || exit 2
+	rsync                          \
+		--archive                  \
+		--one-file-system          \
+		--filter="merge $FILTER"   \
+		--link-dest="$LATEST_LINK" \
+		"$SOURCE" "$DEST"          \
+		|| exit 3
+	rm "$LATEST_LINK"
+	ln -s --relative "$DEST" "$LATEST_LINK"
 }
 
-[[ $# -eq 0 || ! $(typeset -f "$1") ]] && { usage; exit 1; }
-func=$1 && shift
-$func "$@"
-
-# [[ $# = 2 ]]    || err "Usage: backup <source> <dest_dir>"
-# [[ -e $1 ]]     || err "Invalid source"
-# [[ -d $2 ]]     || err "Invalide destination"
-# [[ $1 -ef $2 ]] && err "Source can't be the same as destination"
-
-# SRC_BASENAME=$(basename "$1")
-# DATE_SUFFIX=$(date +%F_%H-%M-%S)
-
-# if [[ -d $1 ]]; then
-# 	DIR="$1"
-# 	FILE=.
-# else
-# 	DIR=$(dirname "$1")
-# 	FILE=$SRC_BASENAME
-# fi
-
-# tar czf "$2/${SRC_BASENAME}_${DATE_SUFFIX}.tar.gz" --dereference --directory="$DIR" "$FILE"
-
+case $1 in
+	edit)
+		$EDITOR "$FILTER" ;;
+	run)
+		run "$2" ;;
+	*)
+		echo "Usage: zapas [edit|run <dest>]"
+esac
